### ISSUE TITLE
Can't connect to PostgreSQL via SSL

### ISSUE THREAD

**Issue by did16** [serge-rider/dbeaver#2133]
Hi
I can not connect via SSL to a PostgreSQL instance. I get the following error message : 
"Could not read SSL key file....".
I have tried with pgadmin 4 and it's OK.
Is it a bug ?
Thanks in advance
Didier

**Comment by serge-rider** [comment]
Did you configure SSL certificates?
If no then you can set SSL factory to NonValidating:
![image](https://user-images.githubusercontent.com/6398845/30294643-7d4edb32-9746-11e7-8559-1017894593e4.png)

**Comment by did16** [comment]
Hi Serge
I have set up SSL certificates 
Root certificate : C:\Users\A74708-A\AppData\Roaming\postgresql\root.crt
SSL Certificate : C:\Users\A74708-A\AppData\Roaming\postgresql\postgresql.crt
SSL Certificate key : C:\Users\A74708-A\AppData\Roaming\postgresql\postgresql.key
but the connexion is impossible.

**Comment by serge-rider** [comment]
Do you use the most recent version of DBeaver?
Some PG SSL issues were fixed recently in #1972

**Comment by did16** [comment]
I use DBeaver version 4.2.0 September 4, 2017
NB : For a security matter , it is very important that we can connect via SSL. 
PG_ADMIN 4 can do it. And I try to impose DBeaver as the main tool for querying our PostgreSQL database.
Thanks in advance 
Didier

**Comment by serge-rider** [comment]
Agreed. This can be a DBeaver bug or some SSL misconfiguration.
Please send error stacktrace (you can get it in Error Log view or in log files: https://github.com/serge-rider/dbeaver/wiki/Log-files)
(note: strip any secure information from logs before posting).

**Comment by did16** [comment]
Hi
Sorry for the delay. I was too busy.
Here are the log-files+
[.dbeaver4.zip](https://github.com/serge-rider/dbeaver/files/1395051/default.dbeaver4.zip)

**Comment by did16** [comment]
oops . I make a mistake. I close the case and it is not fixed !

**Comment by serge-rider** [comment]
Looks like your SSL key certificate is in unsupported (by Java) format.
Check this: https://stackoverflow.com/questions/11621414/reading-an-x-509-certificate-with-java

Converting key cert format could be done with command
```
openssl x509 -outform der -in certificate.pem -out certificate.der
```

**Comment by letientai299** [comment]
This command can be used to convert `client.key` file, in case you've followed [postgres document](https://www.postgresql.org/docs/10/static/libpq-ssl.html) to generate the pair `client.crt` and `client.key`. 

```bash
openssl pkcs8 -topk8 -inform PEM -outform DER -in client.key -out client.pk8 -nocrypt
```

Btw, I really hope DBeaver can support PEM format by default.

**Comment by Minisha** [comment]
is there a way to disable ssl check ?

**Comment by unknow** [comment]
![image](https://user-images.githubusercontent.com/10673/67860180-f96e4700-fafb-11e9-8a83-493a91863e8d.png)
Just select **disable** option in **SSL mode**

**Comment by danilofuchs** [comment]
> Just select **disable** option in **SSL mode**

If you want to connect via SSL, `disable` [is not what you need! It disables SSL](https://www.postgresql.org/docs/8.4/libpq-connect.html#LIBPQ-CONNECT-SSLMODE)

For me, setting SSL Mode to `require` fixed the issue and ensures SSL is used
