### ISSUE TITLE
Cannot select server/database in script editor

### ISSUE THREAD

**Issue by optik-aper** [serge-rider/dbeaver#385]
Version 3.6.5
Ubuntu 15.10

Open DBeaver
Double click a connection to open a script window
Try to change database with the drop down at the top
No clicks registered and no response from the GUI

**Comment by serge-rider** [comment]
What is your database?
Can you post a screenshot?

**Comment by jeisoncp** [comment]
I had the same problem in 3.6.6.

Try move the toolbar to another area of workspace (left, right, bottom), you must be able to click on the select menu.

![dbeaver_bug](https://cloud.githubusercontent.com/assets/7952798/15027746/9e49f8fa-121b-11e6-9d6b-364e1efb1afa.png)

After that, you can move toolbar back. This worked for me.

**Comment by optik-aper** [comment]
I think this might only be an issue when creating the very first script window.  Once I had a bunch of script windows open I was able to select the database normally.  I forgot about this open issue until I saw jeisoncp's reply.  In testing it I did a few things that brought the issue back.

- From a new instance of DBeaver with multiple scripts and table editors open (restored from previously closed sessions) the selection of database and server works.  
- I right-click on a script tab then select "close all"
- Double-click a database connection
- Press "new script"
- It seems to open an arbitrary database on that connection
- Mouse clicks don't register around the selection object (can't drag it anywhere, open the dropdowns, etc.)

Here's an obfuscated screenshot
![dbeaver](https://cloud.githubusercontent.com/assets/8485770/15029593/3f4e9c60-121c-11e6-8a89-38450d1bcc63.jpg)

I'll do some more testing on this.  Is there anything else you would like to see/know?  I realize the screenshot looks completely normal but I have limited time at the moment and can't produce a full series of screenshots.

**Comment by OndrejPacay** [comment]
I can confirm this problem on Kubuntu 16.04  and DBeaver 3.7.1.
When I open a sql file from disk, the server/database is empty and I cannot choose a value (PostgreSQL server). After moving the toolbar I am able to select a DB connection.

**Comment by serge-rider** [comment]
There were a few fixes regarding connection/schema selector in 3.7.5.
Please confirm that this issues was resolved or not.

**Comment by OndrejPacay** [comment]
Hi @serge-rider , 

thank you very much. The issue is resolved for me.

Regards, Ondrej

**Comment by serge-rider** [comment]
Great. Then I'll close it.

**Comment by otono** [comment]
Have this in DBeaver 4.2.3, can't select database, popup window with is empty.

![screenshot from 2017-10-27 11-20-51](https://user-images.githubusercontent.com/195792/32094599-fc7b4e50-bb08-11e7-8d30-3762d246e64c.png)

**Comment by OndrejPacay** [comment]
That is possible other bug.

But while back here I have to say that finally (DB 4.2.1 ... but it is the same since few versions already) the problem was not fixed for me either:
This is the toolbar with the broken DB selector:
![db_toolbar](https://user-images.githubusercontent.com/16879522/32095211-b6edfd84-bb02-11e7-888a-af788a13c6ca.png)

And how it looks after trying to reorder the toolbar by dragging the DB connection part completely to the right:
![db_toolbar_after_dragging_db_connection_to_the_right](https://user-images.githubusercontent.com/16879522/32095241-cd67d170-bb02-11e7-900e-73d06d6b982e.png)

Regards, Ondrej

**Comment by serge-rider** [comment]
@OndrejPacay seems to be a duplicate of #2375. Thanks for report anyway.
